### ISSUE TITLE
Empty versions of `Span::start` and `Span::end` returned on stable compiler

### ISSUE THREAD

**Issue by udoprog** [dtolnay/proc-macro2#237]
Introduced in #166.

With a stable compiler with the `span-locations` feature enabled, we now have a situation where `Span::start` and `Span::end` reports mocked values (`LineColumn { line: 0, column: 0 }`) ([see code](https://docs.rs/proc-macro2/1.0.18/src/proc_macro2/wrapper.rs.html#452)). This is understandable since the underlying function in the compiler is nightly-only behind a feature flag (`proc_macro_span` and rust-lang/rust#54725), but it was somewhat surprising to me that `proc_macro2` falls back to reporting fake spans.

The surprising behavior can be mitigated by documenting in `Span::start` and `Span::end` that their values will be mocked on stable compilers until the relevant features are stabilized. But also, downstream projects which for whatever reason rely on accurate spans don't have a great avenue for erroring at compile time in case the compiler version is too old to support them*.

*: [Span::unwrap](https://docs.rs/proc-macro2/1.0.18/proc_macro2/struct.Span.html#method.unwrap) could in principle be used, but would mean that the code no longer can run outside of a proc_macro.

This is also a potential future compatibility hazard if `start` and `end` were to be broken out into a separate feature flag ([as discussed here](https://github.com/rust-lang/rust/issues/54725#issuecomment-640169091)) to ease the road towards future stabilization. So I'm tying it together here since I'm looking into if and how it can be done.

**Comment by chipsenkbeil** [comment]
I got a bit excited that this was available in stable because it would make hacks like `proc-macro-faithful-display` be available to stable as well. I didn't see anything mentioned in the documentation for `Span::start` or `Span:end` in **proc_macro2** that the values would be mocked.

It makes total sense as I had no idea how proc_macro2 was going to do this in stable if it was to have parity with proc_macro. But a disclaimer in the method docs about it being mocked would be good. 😄
