### ISSUE TITLE
Unknown feature proc_macro_span_shrink

### ISSUE THREAD

**Issue by rohit123sinha456** [dtolnay/proc-macro2#356]
proc-macro2 is a dependent library of the anchor framework. Whenever I am doing a anchor build, the build fails showing the following error :- 

If somebody can please help with this..

error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/rohitsinha/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.46/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

P.S Thanks in advance for any help.

**Comment by taiki-e** [comment]
See https://github.com/dtolnay/proc-macro2/pull/348#issuecomment-1258260927 and subsequent comments.

**Comment by ericcornelissen** [comment]
For your information, wanted to raise that I'm seeing this ~exact error on the nightly toolchain (specifically `rust version 1.72.0-nightly (330727467 2023-06-29)`) while not seeing it on the latest stable version ([reference builds](https://github.com/ericcornelissen/rust-rm/actions/runs/5419446460)):

```log
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.58/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

I'm not quite sure what to make of it because this project's daily scheduled CI also runs tests on the nightly build, but I figured you might want to know (or, if it's preventable, this might help others as well).

**Comment by taiki-e** [comment]
@ericcornelissen The problem you are seeing is different from the problem that was originally reported here.
AFAIK, you need to upgrade proc-macro2 to 1.0.60+, downgrade proc-macro2 to 1.0.43 or before, downgrade the nightly toolchain to nightly-2023-06-28 or before, or use a non-nightly toolchain.
See also https://github.com/rust-lang/rust/issues/113152.
